"""TestSprite integration: clone repo and call TestSprite MCP server to generate tests."""

from __future__ import annotations

import glob
import json
import os
import shutil
import subprocess
import tempfile

from sqlalchemy.orm import Session

from code_ruler.db.models import Rule, TestSpriteResult
from code_ruler.db.repository import create_testsprite_result, update_testsprite_result
from code_ruler.testsprite.mcp_client import MCPClient

TESTSPRITE_API_KEY = os.environ.get("TESTSPRITE_API_KEY", "")
TESTSPRITE_PROXY_URL = os.environ.get("TESTSPRITE_PROXY_URL", "")

# Path to the known working config from a previous bootstrap run
_FALLBACK_CONFIG_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "testsprite_tests", "tmp", "config.json"
)


def _clone_repo(repo_url: str, dest: str) -> None:
    """Shallow clone a repo."""
    subprocess.run(
        ["git", "clone", "--depth", "1", repo_url, dest],
        check=True,
        capture_output=True,
        timeout=120,
    )


def _generate_diff(repo_dir: str, generated_files: list[str]) -> str:
    """Generate a unified diff showing generated test files as new files."""
    diff_lines: list[str] = []
    for fpath in generated_files:
        rel = os.path.relpath(fpath, repo_dir)
        try:
            with open(fpath) as f:
                content = f.read()
        except OSError:
            continue
        lines = content.splitlines()
        diff_lines.append("--- /dev/null")
        diff_lines.append(f"+++ b/{rel}")
        diff_lines.append(f"@@ -0,0 +1,{len(lines)} @@")
        for line in lines:
            diff_lines.append(f"+{line}")
        diff_lines.append("")
    return "\n".join(diff_lines)


def _extract_text(mcp_result: dict) -> str:
    """Extract concatenated text from MCP tool result content blocks."""
    content = mcp_result.get("content", [])
    return "\n".join(
        c.get("text", "") for c in content if c.get("type") == "text"
    )


def _extract_and_run_command(mcp_result: dict, project_dir: str) -> None:
    """Extract the terminal command from MCP next_action response and execute it.

    TestSprite's generate_code_and_execute returns a JSON with next_action
    containing a terminal command that actually runs the test generation.
    """
    response_text = _extract_text(mcp_result)
    try:
        data = json.loads(response_text)
    except (json.JSONDecodeError, TypeError):
        print("[TestSprite] No executable command in MCP response, skipping execution step.")
        return

    actions = data.get("next_action", [])
    for action in actions:
        if action.get("type") == "tool" and "command" in action.get("input", {}):
            cmd = action["input"]["command"]
            print(f"[TestSprite] Running: {cmd}")
            proc = subprocess.run(
                cmd,
                shell=True,
                cwd=project_dir,
                capture_output=True,
                timeout=300,
                env={**os.environ, "API_KEY": TESTSPRITE_API_KEY},
            )
            if proc.returncode != 0:
                stderr = proc.stderr.decode(errors="replace")[:1000]
                print(f"[TestSprite] Command exited {proc.returncode}: {stderr}")
            else:
                print("[TestSprite] Command completed successfully.")
            return
    print("[TestSprite] No terminal command found in MCP response.")


def _read_test_results(project_dir: str) -> dict | list:
    """Read test_results.json written by TestSprite, if it exists."""
    candidates = [
        os.path.join(project_dir, "test_results.json"),
        os.path.join(project_dir, "testsprite_tests", "tmp", "test_results.json"),
        os.path.join(project_dir, ".testsprite", "test_results.json"),
    ]
    for path in candidates:
        if os.path.isfile(path):
            with open(path) as f:
                return json.load(f)
    return {}


def _find_generated_test_files(project_dir: str) -> list[str]:
    """Find test files generated by TestSprite in the project directory."""
    search_dirs = [project_dir, os.path.join(project_dir, "testsprite_tests")]
    test_patterns = ["test_*.py", "*_test.py", "*.test.ts", "*.test.js", "*.spec.ts", "*.spec.js", "TC*.py"]
    files: list[str] = []
    for search_dir in search_dirs:
        for pat in test_patterns:
            files.extend(glob.glob(os.path.join(search_dir, "**", pat), recursive=True))
    return sorted(set(files))


def _read_generated_tests(project_dir: str) -> str:
    """Read and concatenate all generated test files."""
    files = _find_generated_test_files(project_dir)
    parts: list[str] = []
    for fpath in files:
        rel = os.path.relpath(fpath, project_dir)
        try:
            with open(fpath) as f:
                parts.append(f"# {rel}\n{f.read()}")
        except OSError:
            continue
    return "\n\n".join(parts)


def _get_proxy_url() -> str:
    """Get the TestSprite proxy URL from env var or fallback config."""
    if TESTSPRITE_PROXY_URL:
        return TESTSPRITE_PROXY_URL
    # Try reading from the existing working config
    fallback = os.path.normpath(_FALLBACK_CONFIG_PATH)
    if os.path.isfile(fallback):
        try:
            with open(fallback) as f:
                cfg = json.load(f)
            proxy = cfg.get("proxy", "")
            if proxy:
                return proxy
        except (json.JSONDecodeError, OSError):
            pass
    return ""


def _write_testsprite_config(project_dir: str, project_name: str, rule: Rule) -> None:
    """Write testsprite_tests/tmp/config.json with all required fields including proxy."""
    config_dir = os.path.join(project_dir, "testsprite_tests", "tmp")
    os.makedirs(config_dir, exist_ok=True)

    additional = _build_additional_instruction(rule)
    proxy = _get_proxy_url()

    config: dict = {
        "status": "init",
        "scope": "codebase",
        "type": "backend",
        "testType": "backend",
        "localEndpoint": "http://localhost:8000/",
        "serverPort": 39239,
        "executionArgs": {
            "projectName": project_name,
            "projectPath": project_dir,
            "testIds": [],
            "additionalInstruction": additional,
            "envs": {
                "API_KEY": TESTSPRITE_API_KEY,
            },
        },
    }
    if proxy:
        config["proxy"] = proxy

    config_path = os.path.join(config_dir, "config.json")
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)
    print(f"[TestSprite] Wrote config to {config_path} (proxy={'yes' if proxy else 'NO'})")


def _build_additional_instruction(rule: Rule) -> str:
    """Build the additionalInstruction string for TestSprite from a rule."""
    parts = [
        "Generate exactly 1-4 focused unit tests for this single coding rule.",
        f"Rule: {rule.title}",
        f"Description: {rule.description}",
    ]
    if rule.positive_example:
        parts.append(f"Positive example (code that follows the rule):\n{rule.positive_example}")
    if rule.negative_example:
        parts.append(f"Negative example (code that violates the rule):\n{rule.negative_example}")
    parts.append(
        "Do NOT open a browser or Chrome. Do NOT test the entire codebase. "
        "Only generate tests that verify this specific rule is enforced. "
        "Keep it to 1-4 small, focused test cases."
    )
    return "\n".join(parts)


def _write_test_plan(project_dir: str, rule: Rule, project_name: str = "project") -> list[dict]:
    """Write a minimal test plan JSON so generate_code_and_execute has something to work with."""
    plan = [
        {
            "id": "TC001",
            "title": f"detect violation of: {rule.title}",
            "description": (
                f"Test that code violating the rule '{rule.title}' is detected. "
                f"Rule: {rule.description}"
            ),
        },
    ]
    if rule.positive_example:
        plan.append({
            "id": "TC002",
            "title": f"accept compliant code for: {rule.title}",
            "description": (
                f"Test that code following the rule '{rule.title}' passes. "
                f"Positive example:\n{rule.positive_example}"
            ),
        })
    if rule.negative_example:
        plan.append({
            "id": "TC003",
            "title": f"reject non-compliant code for: {rule.title}",
            "description": (
                f"Test that code violating the rule '{rule.title}' is caught. "
                f"Negative example:\n{rule.negative_example}"
            ),
        })
    ts_dir = os.path.join(project_dir, "testsprite_tests")
    os.makedirs(os.path.join(ts_dir, "tmp"), exist_ok=True)

    plan_path = os.path.join(ts_dir, "testsprite_backend_test_plan.json")
    with open(plan_path, "w") as f:
        json.dump(plan, f, indent=2)
    print(f"[TestSprite] Wrote test plan ({len(plan)} cases) to {plan_path}")

    # Write minimal standard_prd.json (required by generateCodeAndExecute)
    prd = {
        "meta": {"project": project_name, "date": "2026-01-01", "prepared_by": "code-ruler"},
        "product_overview": f"Testing rule: {rule.title}. {rule.description}",
        "core_goals": [f"Enforce rule: {rule.title}"],
        "features": [{
            "name": rule.title,
            "description": rule.description,
            "user_flows": [
                f"Detect code that violates: {rule.title}",
                f"Accept code that follows: {rule.title}",
            ],
        }],
    }
    prd_path = os.path.join(ts_dir, "standard_prd.json")
    with open(prd_path, "w") as f:
        json.dump(prd, f, indent=2)

    # Write minimal code_summary.yaml (may be required)
    summary_path = os.path.join(ts_dir, "tmp", "code_summary.yaml")
    with open(summary_path, "w") as f:
        f.write(f"project: {project_name}\n")
        f.write(f"description: Testing rule - {rule.title}\n")
        f.write(f"type: backend\n")

    return plan


def generate_tests(session: Session, rule: Rule, repo_url: str) -> TestSpriteResult:
    """Clone repo and call TestSprite MCP server to generate unit tests for a rule.

    Steps:
    1. Create DB record with status="cloning"
    2. git clone --depth 1 to temp dir
    3. Write .testsprite/config.json (with proxy — no bootstrap, no Chrome)
    4. Write a focused test plan based on the rule
    5. Call generate_code_and_execute via MCP, then execute the returned command
    6. Collect results and update DB record
    """
    result = create_testsprite_result(
        session,
        rule_id=rule.id,
        repo_url=repo_url,
        status="cloning",
    )
    session.commit()

    tmpdir = tempfile.mkdtemp(prefix="testsprite_")
    try:
        # Step 1: Clone
        print(f"[TestSprite] Cloning {repo_url}...")
        _clone_repo(repo_url, tmpdir)

        project_name = os.path.basename(tmpdir)

        # Step 2: Write config (no bootstrap — no Chrome)
        _write_testsprite_config(tmpdir, project_name, rule)

        # Step 3: Write a focused test plan from the rule
        test_plan = _write_test_plan(tmpdir, rule, project_name)
        update_testsprite_result(session, result, status="generating", test_plan_json=test_plan)
        session.commit()

        # Step 4: Generate and execute tests via MCP
        update_testsprite_result(session, result, status="running")
        session.commit()

        with MCPClient() as mcp:
            print("[TestSprite] Generating and executing tests...")
            exec_result = mcp.call_tool("testsprite_generate_code_and_execute", {
                "projectName": project_name,
                "projectPath": tmpdir,
                "testIds": [],
                "additionalInstruction": _build_additional_instruction(rule),
            })

        # Step 5: Execute the terminal command from MCP response
        _extract_and_run_command(exec_result, tmpdir)

        # Step 6: Collect results from filesystem
        test_results = _read_test_results(tmpdir)
        generated_tests_content = _read_generated_tests(tmpdir)
        generated_files = _find_generated_test_files(tmpdir)

        # Generate diff
        diff = ""
        if generated_files:
            diff = _generate_diff(tmpdir, generated_files)
        if not diff and generated_tests_content:
            lines = generated_tests_content.splitlines()
            diff = "\n".join([
                "--- /dev/null",
                f"+++ b/tests/{rule.slug}_test.py",
                f"@@ -0,0 +1,{len(lines)} @@",
            ] + [f"+{l}" for l in lines])

        update_testsprite_result(
            session,
            result,
            status="completed",
            generated_tests=generated_tests_content,
            test_results_json=test_results,
            diff=diff,
        )
        session.commit()
        print(f"[TestSprite] Completed successfully for rule '{rule.slug}'.")
        return result

    except Exception as e:
        update_testsprite_result(
            session,
            result,
            status="failed",
            error_message=str(e)[:2000],
        )
        session.commit()
        print(f"[TestSprite] Failed: {e}")
        raise

    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
